version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: project-quem-foi-para-o-mar
    volumes:
      - .:/quem-foi-para-o-mar_service
    ports:
      - "8000:8000"
